name: Update LeetCode Progress

on: [pull_request]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: cargo install reqwest tokio serde_json

      - name: Run update script
        run: cargo run --bin update_readme

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update LeetCode progress" || exit 0
          git push
